"""create hosts, projects, project_hosts tables

Revision ID: 13fc49f28b6b
Revises: 
Create Date: 2026-05-11 14:31:08.772256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fc49f28b6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS ref")
    
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ref'
    )
    op.create_index(op.f('ix_ref_hosts_hostname'), 'hosts', ['hostname'], unique=True, schema='ref')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ref'
    )
    op.create_index(op.f('ix_ref_projects_name'), 'projects', ['name'], unique=True, schema='ref')
    op.create_table('project_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['ref.hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['ref.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'host_id', 'env', name='uq_project_hosts_project_host_env'),
    schema='ref'
    )
    op.create_index(op.f('ix_ref_project_hosts_env'), 'project_hosts', ['env'], unique=False, schema='ref')
    op.create_index(op.f('ix_ref_project_hosts_host_id'), 'project_hosts', ['host_id'], unique=False, schema='ref')
    op.create_index(op.f('ix_ref_project_hosts_project_id'), 'project_hosts', ['project_id'], unique=False, schema='ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_project_hosts_project_id'), table_name='project_hosts', schema='ref')
    op.drop_index(op.f('ix_ref_project_hosts_host_id'), table_name='project_hosts', schema='ref')
    op.drop_index(op.f('ix_ref_project_hosts_env'), table_name='project_hosts', schema='ref')
    op.drop_table('project_hosts', schema='ref')
    op.drop_index(op.f('ix_ref_projects_name'), table_name='projects', schema='ref')
    op.drop_table('projects', schema='ref')
    op.drop_index(op.f('ix_ref_hosts_hostname'), table_name='hosts', schema='ref')
    op.drop_table('hosts', schema='ref')
    # ### end Alembic commands ###
